# Generated by Django 6.1.1 on 2026-09-15 05:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('duplicate', 'Duplicate Invoice'), ('unusual_amount', 'Unusual Amount'), ('missing_field', 'Missing Field'), ('calculation', 'Calculation Mismatch'), ('vendor', 'Vendor Anomaly'), ('gst', 'GST Anomaly'), ('other', 'Other')], max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('cloud', 'Cloud Infrastructure'), ('travel', 'Travel'), ('office', 'Office Supplies'), ('marketing', 'Marketing'), ('professional', 'Professional Services'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('expense_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_number_per_owner_vendor',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='unique_vendor_per_owner',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='tax_id',
            new_name='gstin',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='gstin',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('cloud', 'Cloud Infrastructure'), ('travel', 'Travel'), ('office', 'Office Supplies'), ('marketing', 'Marketing'), ('professional', 'Professional Services'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=24),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('validated', 'Validated'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('user', 'vendor', 'invoice_number'), name='unique_number_per_user_vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_vendor_per_user'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
